---
- name: Restart Semaphore
  command: "docker restart {{ item }}"
  with_items:
    - "{{ semaphore_name }}"

- name: Remove Semaphore
  command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ semaphore_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
